const BUSINESS_TYPE_GROUPS = [
  {
    label: 'Food & Dining',
    types: [
      { value: 'restaurant', label: 'Restaurant' },
      { value: 'cafe', label: 'Cafe' },
      { value: 'bar', label: 'Bar' },
      { value: 'bakery', label: 'Bakery' },
      { value: 'pizza_restaurant', label: 'Pizza Restaurant' },
      { value: 'ice_cream_shop', label: 'Ice Cream Shop' },
      { value: 'coffee_shop', label: 'Coffee Shop' },
      { value: 'meal_delivery', label: 'Meal Delivery' },
      { value: 'meal_takeaway', label: 'Meal Takeaway' },
      { value: 'night_club', label: 'Night Club' },
    ],
  },
  {
    label: 'Shopping & Retail',
    types: [
      { value: 'store', label: 'General Store' },
      { value: 'grocery_store', label: 'Grocery Store' },
      { value: 'convenience_store', label: 'Convenience Store' },
      { value: 'clothing_store', label: 'Clothing Store' },
      { value: 'shoe_store', label: 'Shoe Store' },
      { value: 'jewelry_store', label: 'Jewelry Store' },
      { value: 'book_store', label: 'Book Store' },
      { value: 'gift_shop', label: 'Gift Shop' },
      { value: 'bicycle_store', label: 'Bicycle Store' },
      { value: 'pet_store', label: 'Pet Store' },
      { value: 'sporting_goods_store', label: 'Sporting Goods' },
      { value: 'hardware_store', label: 'Hardware Store' },
      { value: 'electronics_store', label: 'Electronics Store' },
      { value: 'furniture_store', label: 'Furniture Store' },
      { value: 'home_goods_store', label: 'Home Goods' },
      { value: 'home_improvement_store', label: 'Home Improvement' },
      { value: 'liquor_store', label: 'Liquor Store' },
      { value: 'florist', label: 'Florist' },
      { value: 'discount_store', label: 'Discount Store' },
    ],
  },
  {
    label: 'Health & Medical',
    types: [
      { value: 'doctor', label: 'Doctor' },
      { value: 'dentist', label: 'Dentist' },
      { value: 'pharmacy', label: 'Pharmacy' },
      { value: 'veterinary_care', label: 'Veterinarian' },
      { value: 'physiotherapist', label: 'Physiotherapist' },
      { value: 'optician', label: 'Optician' },
      { value: 'medical_lab', label: 'Medical Lab' },
    ],
  },
  {
    label: 'Beauty & Wellness',
    types: [
      { value: 'beauty_salon', label: 'Beauty Salon' },
      { value: 'hair_salon', label: 'Hair Salon' },
      { value: 'hair_care', label: 'Hair Care' },
      { value: 'nail_salon', label: 'Nail Salon' },
      { value: 'barbershop', label: 'Barbershop' },
      { value: 'spa', label: 'Spa' },
      { value: 'tattoo_shop', label: 'Tattoo Shop' },
      { value: 'gym', label: 'Gym / Fitness' },
    ],
  },
  {
    label: 'Home & Trade Services',
    types: [
      { value: 'plumber', label: 'Plumber' },
      { value: 'electrician', label: 'Electrician' },
      { value: 'roofing_contractor', label: 'Roofing' },
      { value: 'painter', label: 'Painter' },
      { value: 'locksmith', label: 'Locksmith' },
      { value: 'moving_company', label: 'Moving Company' },
      { value: 'laundry', label: 'Laundry' },
      { value: 'shoe_repair', label: 'Shoe Repair' },
      { value: 'tailor', label: 'Tailor' },
      { value: 'funeral_home', label: 'Funeral Home' },
      { value: 'storage', label: 'Storage' },
    ],
  },
  {
    label: 'Auto & Transport',
    types: [
      { value: 'car_repair', label: 'Auto Repair' },
      { value: 'car_wash', label: 'Car Wash' },
      { value: 'car_dealer', label: 'Car Dealer' },
      { value: 'car_rental', label: 'Car Rental' },
      { value: 'gas_station', label: 'Gas Station' },
      { value: 'electric_vehicle_charging_station', label: 'EV Charging' },
    ],
  },
  {
    label: 'Professional & Financial',
    types: [
      { value: 'lawyer', label: 'Lawyer' },
      { value: 'accounting', label: 'Accounting' },
      { value: 'real_estate_agency', label: 'Real Estate' },
      { value: 'insurance_agency', label: 'Insurance' },
      { value: 'consultant', label: 'Consultant' },
      { value: 'travel_agency', label: 'Travel Agency' },
      { value: 'courier_service', label: 'Courier Service' },
    ],
  },
  {
    label: 'Arts & Entertainment',
    types: [
      { value: 'art_gallery', label: 'Art Gallery' },
      { value: 'museum', label: 'Museum' },
      { value: 'movie_theater', label: 'Movie Theater' },
      { value: 'bowling_alley', label: 'Bowling Alley' },
      { value: 'amusement_center', label: 'Amusement Center' },
      { value: 'event_venue', label: 'Event Venue' },
      { value: 'wedding_venue', label: 'Wedding Venue' },
    ],
  },
  {
    label: 'Lodging',
    types: [
      { value: 'hotel', label: 'Hotel' },
      { value: 'bed_and_breakfast', label: 'Bed & Breakfast' },
      { value: 'campground', label: 'Campground' },
      { value: 'rv_park', label: 'RV Park' },
    ],
  },
  {
    label: 'Education & Childcare',
    types: [
      { value: 'school', label: 'School' },
      { value: 'preschool', label: 'Preschool' },
      { value: 'child_care_agency', label: 'Child Care' },
    ],
  },
  {
    label: 'Other Niche',
    types: [
      { value: 'photo_studio', label: 'Photo Studio' },
      { value: 'phone_repair', label: 'Phone Repair' },
      { value: 'marina', label: 'Marina' },
      { value: 'golf_course', label: 'Golf Course' },
    ],
  },
];

const RATING_OPTIONS = [
  { value: 0, label: 'Any Rating' },
  { value: 3, label: '3+ Stars' },
  { value: 3.5, label: '3.5+ Stars' },
  { value: 4, label: '4+ Stars' },
  { value: 4.5, label: '4.5+ Stars' },
];

export { BUSINESS_TYPE_GROUPS, RATING_OPTIONS };
