from flask import Blueprint, request, jsonify, current_app, g
from app import db
from app.models import Template
from app.services.claude_service import ClaudeService, clean_company_name
import re
import os

templates_bp = Blueprint('templates', __name__)

def extract_variables(text):
    """Extract {{variable}} placeholders from text."""
    pattern = r'\{\{(\w+)\}\}'
    return list(set(re.findall(pattern, text)))

@templates_bp.route('', methods=['GET'])
def list_templates():
    """List all templates."""
    templates = Template.query.filter_by(workspace_id=g.workspace_id).order_by(Template.updated_at.desc()).all()
    return jsonify([t.to_dict() for t in templates])

@templates_bp.route('/<int:id>', methods=['GET'])
def get_template(id):
    """Get a single template."""
    template = Template.query.get_or_404(id)
    return jsonify(template.to_dict())

@templates_bp.route('', methods=['POST'])
def create_template():
    """Create a new template."""
    data = request.get_json()

    if not data.get('name') or not data.get('subject') or not data.get('body'):
        return jsonify({'error': 'Name, subject, and body are required'}), 400

    # Auto-detect variables from subject and body
    variables = extract_variables(data['subject'] + ' ' + data['body'])

    template = Template(
        workspace_id=g.workspace_id,
        name=data['name'],
        subject=data['subject'],
        body=data['body']
    )
    template.set_variables(variables)

    db.session.add(template)
    db.session.commit()

    return jsonify(template.to_dict()), 201

@templates_bp.route('/<int:id>', methods=['PUT'])
def update_template(id):
    """Update a template."""
    template = Template.query.get_or_404(id)
    data = request.get_json()

    if 'name' in data:
        template.name = data['name']
    if 'subject' in data:
        template.subject = data['subject']
    if 'body' in data:
        template.body = data['body']

    # Re-detect variables
    variables = extract_variables(template.subject + ' ' + template.body)
    template.set_variables(variables)

    db.session.commit()
    return jsonify(template.to_dict())

@templates_bp.route('/<int:id>', methods=['DELETE'])
def delete_template(id):
    """Delete a template."""
    template = Template.query.get_or_404(id)
    db.session.delete(template)
    db.session.commit()
    return jsonify({'success': True})

@templates_bp.route('/<int:id>/preview', methods=['POST'])
def preview_template(id):
    """Preview template with sample data."""
    template = Template.query.get_or_404(id)
    data = request.get_json()
    sample_data = data.get('sample_data', {})

    # Replace variables in subject and body
    subject = template.subject
    body = template.body

    for key, value in sample_data.items():
        placeholder = '{{' + key + '}}'
        cleaned = clean_company_name(str(value)) if key == 'company' else str(value)
        subject = subject.replace(placeholder, cleaned)
        body = body.replace(placeholder, cleaned)

    return jsonify({
        'subject': subject,
        'body': body,
        'variables': template.get_variables()
    })


@templates_bp.route('/variables', methods=['GET'])
def list_variables():
    """Return all available template variables with descriptions."""
    variables = [
        # Core variables — always available, auto-filled from recipient data
        {
            'name': 'name',
            'category': 'core',
            'description': "Recipient's first name",
            'example': 'Sarah',
            'source': 'Auto-filled from recipient/CSV name column',
        },
        {
            'name': 'email',
            'category': 'core',
            'description': "Recipient's email address",
            'example': 'sarah@acme.com',
            'source': 'Auto-filled from recipient/CSV email column',
        },
        {
            'name': 'company',
            'category': 'core',
            'description': "Recipient's company name (cleaned of URLs/suffixes)",
            'example': 'Acme Corp',
            'source': 'Auto-filled from recipient/CSV company column',
        },
        # Special AI-generated variable
        {
            'name': 'website_insights',
            'category': 'special',
            'description': 'AI-generated observations about the recipient\'s website (2 specific improvement opportunities)',
            'example': 'your pricing page could benefit from social proof, and your onboarding flow has a few extra steps that might cause drop-off',
            'source': "Auto-generated by analyzing the recipient's website at send time",
        },
        # Competitor discovery variables — populated via Tavily web search
        {
            'name': 'competitor1',
            'category': 'special',
            'description': "Top competitor of the recipient's company",
            'example': 'HubSpot',
            'source': 'Auto-discovered via web search when Competitor Discovery is enabled on the campaign',
        },
        {
            'name': 'competitor2',
            'category': 'special',
            'description': "Second competitor of the recipient's company",
            'example': 'Salesforce',
            'source': 'Auto-discovered via web search when Competitor Discovery is enabled on the campaign',
        },
        {
            'name': 'competitors',
            'category': 'special',
            'description': 'Comma-separated list of all discovered competitors',
            'example': 'HubSpot, Salesforce, Pipedrive',
            'source': 'Auto-discovered via web search when Competitor Discovery is enabled on the campaign',
        },
        # Common custom fields — populated from CSV columns
        {
            'name': 'title',
            'category': 'custom',
            'description': "Recipient's job title or role",
            'example': 'VP of Engineering',
            'source': 'CSV column: title, role, or job_title',
        },
        {
            'name': 'industry',
            'category': 'custom',
            'description': "Recipient's industry or sector",
            'example': 'FinTech',
            'source': 'CSV column: industry or sector',
        },
        {
            'name': 'company_size',
            'category': 'custom',
            'description': 'Number of employees at the company',
            'example': '50-200',
            'source': 'CSV column: company_size or employees',
        },
        {
            'name': 'funding_stage',
            'category': 'custom',
            'description': 'Current funding round or stage',
            'example': 'Series A',
            'source': 'CSV column: funding_stage or funding',
        },
        {
            'name': 'revenue',
            'category': 'custom',
            'description': 'Company revenue or ARR',
            'example': '$2M ARR',
            'source': 'CSV column: revenue or arr',
        },
        {
            'name': 'recent_news',
            'category': 'custom',
            'description': 'Recent company news or announcements',
            'example': 'Just closed a $10M Series A led by Sequoia',
            'source': 'CSV column: recent_news or news',
        },
        {
            'name': 'pain_points',
            'category': 'custom',
            'description': 'Known challenges or pain points',
            'example': 'Struggling with customer churn in the first 90 days',
            'source': 'CSV column: pain_points or challenges',
        },
        {
            'name': 'referral',
            'category': 'custom',
            'description': 'Mutual connection or referral source',
            'example': 'Mike from Y Combinator',
            'source': 'CSV column: referral, mutual_connection, or referred_by',
        },
        {
            'name': 'linkedin_url',
            'category': 'custom',
            'description': "Recipient's LinkedIn profile URL",
            'example': 'https://linkedin.com/in/sarahsmith',
            'source': 'CSV column: linkedin or linkedin_url',
        },
        {
            'name': 'twitter',
            'category': 'custom',
            'description': "Recipient's Twitter/X handle",
            'example': '@sarahsmith',
            'source': 'CSV column: twitter or twitter_handle',
        },
        {
            'name': 'context',
            'category': 'custom',
            'description': 'Research notes or additional context about the recipient',
            'example': 'Met at SaaStr, interested in our analytics product',
            'source': 'CSV column: context, notes, or research_notes',
        },
        {
            'name': 'previous_interaction',
            'category': 'custom',
            'description': 'Details about a previous meeting or interaction',
            'example': 'Chatted at the React Summit afterparty',
            'source': 'CSV column: previous_interaction or met_at',
        },
        {
            'name': 'recent_launch',
            'category': 'custom',
            'description': 'Recent product or feature launch',
            'example': 'Just launched their AI-powered search feature',
            'source': 'CSV column: recent_launch or product_launch',
        },
    ]

    categories = [
        {
            'id': 'core',
            'label': 'Core Variables',
            'description': 'Always available. Auto-filled from recipient data or CSV upload.',
        },
        {
            'id': 'special',
            'label': 'AI-Generated',
            'description': 'Automatically generated by AI at send time.',
        },
        {
            'id': 'custom',
            'label': 'Custom Fields',
            'description': 'Populated from CSV columns. You can also add any custom column name in your CSV and use it as {{column_name}}.',
        },
    ]

    return jsonify({'variables': variables, 'categories': categories})


@templates_bp.route('/generate', methods=['POST'])
def generate_template():
    """Generate a template using Claude AI."""
    data = request.get_json()

    purpose = data.get('purpose')
    if not purpose:
        return jsonify({'error': 'Purpose is required'}), 400

    # Get API key from settings
    from app.models import Settings
    api_key = Settings.get('anthropic_api_key')

    if not api_key:
        api_key = os.environ.get('ANTHROPIC_API_KEY')

    if not api_key:
        return jsonify({'error': 'Anthropic API key not configured. Please add it in Settings.'}), 400

    try:
        claude = ClaudeService(api_key)
        result = claude.generate_template(
            purpose=purpose,
            target_audience=data.get('target_audience'),
            tone=data.get('tone', 'professional but casual'),
            key_points=data.get('key_points'),
            call_to_action=data.get('call_to_action'),
            length=data.get('length', 'short')
        )
        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@templates_bp.route('/refine', methods=['POST'])
def refine_template():
    """Refine an AI-generated template based on user feedback."""
    data = request.get_json()

    feedback = data.get('feedback')
    current_subject = data.get('subject')
    current_body = data.get('body')
    current_name = data.get('name', 'Template')

    if not feedback:
        return jsonify({'error': 'Feedback is required'}), 400
    if not current_subject or not current_body:
        return jsonify({'error': 'Current template subject and body are required'}), 400

    # Get API key from settings
    from app.models import Settings
    api_key = Settings.get('anthropic_api_key')

    if not api_key:
        api_key = os.environ.get('ANTHROPIC_API_KEY')

    if not api_key:
        return jsonify({'error': 'Anthropic API key not configured. Please add it in Settings.'}), 400

    try:
        claude = ClaudeService(api_key)
        result = claude.refine_template(
            current_subject=current_subject,
            current_body=current_body,
            current_name=current_name,
            feedback=feedback,
            original_purpose=data.get('purpose')
        )
        return jsonify(result)
    except Exception as e:
        return jsonify({'error': str(e)}), 500
